-- 코드를 입력하세요
  SELECT    INGREDIENT_TYPE
           ,SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM    FIRST_HALF      T1
           ,ICECREAM_INFO   T2
   WHERE    T1.FLAVOR   =   T2.FLAVOR
GROUP BY    INGREDIENT_TYPE
ORDER BY    TOTAL_ORDER ASC
;